-- Script de migración del modelo Socio/Asociado al modelo Familia/Miembro
-- Este script convierte la estructura de datos existente al nuevo modelo de negocio

BEGIN;
-- 1. Crear tablas temporales para guardar datos originales
CREATE TABLE IF NOT EXISTS socios_backup AS TABLE socios;
CREATE TABLE IF NOT EXISTS asociados_backup AS TABLE asociados;
CREATE TABLE IF NOT EXISTS direcciones_backup AS TABLE direcciones;

-- 2. Crear la tabla Familia con la nueva estructura
CREATE TABLE IF NOT EXISTS familias (
    id INTEGER PRIMARY KEY,
    id_socio INTEGER UNIQUE NOT NULL,
    apellidos VARCHAR(30) NOT NULL,
    id_direccion INTEGER,
    FOREIGN KEY (id_socio) REFERENCES socios(id) ON DELETE CASCADE,
    FOREIGN KEY (id_direccion) REFERENCES direcciones_backup(id) ON DELETE SET NULL
);

-- 3. Migrar direcciones a referencia de familias
ALTER TABLE direcciones_backup ADD COLUMN id_familia_target INTEGER;

-- 4. Insertar familias a partir de los socios existentes
INSERT INTO familias (id_socio, apellidos)
SELECT 
    id, 
    apellido1re || ' ' || apellido2do,
    (SELECT d.id FROM direcciones_backup d WHERE d.id_socio = s.id LIMIT 1) as id_direccion
FROM socios s;

-- 5. Insertar miembros a partir de socios (miembros principales)
CREATE TABLE IF NOT EXISTS miembros (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    id_familia INTEGER NOT NULL,
    id_miembro INTEGER NOT NULL,
    tipo_documento VARCHAR(3) NOT NULL,
    numero_documento VARCHAR(15) UNIQUE,
    nombres VARCHAR(30),
    apellido1re VARCHAR(15),
    apellido2do VARCHAR(15),
    fecha_nacimiento DATE,
    genero VARCHAR(1),
    nacionalidad INTEGER,
    pais_nacimiento INTEGER,
    estado_nacimiento INTEGER,
    ciudad_nacimiento INTEGER,
    numero_telefonico VARCHAR(20),
    ocupacion VARCHAR(100),
    profesion VARCHAR(100),
    esPrincipal INTEGER DEFAULT 0,
    alimentacion1 INTEGER DEFAULT 1,
    FOREIGN KEY (id_familia) REFERENCES familias(id) ON DELETE CASCADE,
    UNIQUE (id_familia, id_miembro)
);

-- 6. Insertar miembros principales a partir de los datos de socios
INSERT INTO miembros (
    id_familia,
    id_miembro,
    tipo_documento,
    numero_documento,
    nombres,
    apellido1re,
    apellido2do,
    fecha_nacimiento,
    genero,
    nacionalidad,
    pais_nacimiento,
    estado_nacimiento,
    ciudad_nacimiento,
    numero_telefonico,
    ocupacion,
    profesion,
    esPrincipal
)
SELECT 
    f.id as id_familia,
    1 as id_miembro, -- El miembro principal siempre es 1
    'DNI' as tipo_documento, -- Usar DNI por defecto
    COALESCE((SELECT a.numero_documento FROM asociados_backup a 
              WHERE a.id_socio = s.id AND a.miembroPrincipal = 1 LIMIT 1), 
             'TEMP' || s.id) as numero_documento,
    s.nombres,
    s.apellido1re,
    s.apellido2do,
    CURRENT_DATE as fecha_nacimiento, -- Valor temporal
    'M' as genero, -- Valor temporal
    1 as nacionalidad, -- Valor temporal
    1 as pais_nacimiento,
    NULL as estado_nacimiento,
    NULL as ciudad_nacimiento,
    NULL as numero_telefonico,
    NULL as ocupacion,
    NULL as profesion,
    1 as esPrincipal -- Es miembro principal
FROM socios s
JOIN familias f ON f.id_socio = s.id;

-- 7. Insertar asociados como miembros secundarios
INSERT INTO miembros (
    id_familia,
    id_miembro,
    tipo_documento,
    numero_documento,
    nombres,
    apellido1re,
    apellido2do,
    fecha_nacimiento,
    genero,
    nacionalidad,
    pais_nacimiento,
    estado_nacimiento,
    ciudad_nacimiento,
    numero_telefonico,
    ocupacion,
    profesion,
    esPrincipal,
    alimentacion1
)
SELECT 
    f.id as id_familia,
    a.id_asociado as id_miembro,
    a.tipo_documento,
    a.numero_documento,
    a.nombres,
    a.apellido1re,
    a.apellido2do,
    a.fecha_nacimiento,
    a.genero,
    a.nacionalidad,
    a.pais_nacimiento,
    a.estado_nacimiento,
    a.ciudad_nacimiento,
    a.numero_telefonico,
    a.ocupacion,
    a.profesion,
    a.miembroPrincipal, -- Mantener el valor original
    a.alimentacion1
FROM asociados_backup a
JOIN socios s ON s.id = a.id_socio
JOIN familias f ON f.id_socio = s.id
WHERE a.miembroPrincipal = 0; -- Solo asociados no principales

-- 8. Migrar direcciones a familias
UPDATE direcciones_backup SET id_familia_target = 
    (SELECT f.id FROM familias f WHERE f.id_socio = direcciones_backup.id_socio);

-- 9. Crear tabla de direcciones con referencia a familia
CREATE TABLE IF NOT EXISTS direcciones_new AS 
SELECT 
    id,
    id_familia_target as id_familia,
    id_tipo_via,
    nombre_via,
    numero,
    portal,
    piso,
    apartamento,
    pueblo,
    nombre_pueblo,
    codigo_postal,
    activa
FROM direcciones_backup;

-- 10. Agregar credenciales a socios para el nuevo modelo de autenticación
ALTER TABLE socios ADD COLUMN IF NOT EXISTS usuario VARCHAR(50) UNIQUE;
ALTER TABLE socios ADD COLUMN IF NOT EXISTS password VARCHAR(255);

-- 11. Generar credenciales de usuario/password para miembros principales
UPDATE socios SET 
    usuario = COALESCE(
        (SELECT REPLACE(REPLACE(REPLACE(a.numero_documento, '\-', ''), ' ', '_'), '_', '') 
         FROM asociados_backup a WHERE a.id_socio = socios.id AND a.miembroPrincipal = 1 LIMIT 1),
        'user' || id
    ),
    password = '$2b$10$dummyGeneratedPasswordHash' -- Esto debe ser actualizado después de la migración
WHERE id IN (SELECT id_socio FROM familias);

-- 12. Actualizar familias con la dirección principal
UPDATE familias SET id_direccion = 
    (SELECT id FROM direcciones_new WHERE id_familia = familias.id LIMIT 1);

-- 13. Reemplazar tablas originales por las nuevas
DROP TABLE IF EXISTS direcciones;
ALTER TABLE direcciones_new RENAME TO direcciones;

-- 14. Actualizar foreign keys para la tabla Familia
ALTER TABLE familias DROP CONSTRAINT IF EXISTS familias_id_direccion_fkey;
ALTER TABLE familias ADD CONSTRAINT familias_id_direccion_fkey 
    FOREIGN KEY (id_direccion) REFERENCES direcciones(id);

-- 15. Crear índices para mejor rendimiento
CREATE INDEX IF NOT EXISTS idx_miembros_familia_id ON miembros(id_familia);
CREATE INDEX IF NOT EXISTS idx_miembros_principal ON miembros(esPrincipal);
CREATE INDEX IF NOT EXISTS idx_direcciones_familia ON direcciones(id_familia);

-- 16. Validación final
SELECT 'Migración completada. Proceder a verificar integridad de datos' as mensaje;

-- Conteo de registros migrados
SELECT 'Socios migrados:', (SELECT COUNT(*) FROM socios_backup) as count;
SELECT 'Familias creadas:', (SELECT COUNT(*) FROM familias) as count;
SELECT 'Miembros principales:', (SELECT COUNT(*) FROM miembros WHERE esPrincipal = 1) as count;
SELECT 'Miembros secundarios:', (SELECT COUNT(*) FROM miembros WHERE esPrincipal = 0) as count;
SELECT 'Direcciones migradas:', (SELECT COUNT(*) FROM direcciones) as count;

COMMIT;